ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "Weights & Biases"
  site-url: "https://fastai.github.io/wandb-nbdev"
  description: "Demo of Weights & Biases documentation using nbdev"
  twitter-card: true
  open-graph: true
  page-navigation: true
  repo-branch: master
  repo-url: "https://github.com/fastai/wandb-nbdev"
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/fastai/wandb-nbdev"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
